"""
Cultivation information.
"""


# MARK: - Keys
CULTIVATION_NAME_KEY = "name"
CULTIVATION_COST_KEY = "cost"
CULTIVATION_TIER_KEY = "tier"


# MARK: - Methods
INFUSE_WITH_MAGIC = {
    CULTIVATION_NAME_KEY: "Infuse with magic (0G)",
    CULTIVATION_COST_KEY: 0,
    CULTIVATION_TIER_KEY: 1,
}

POUR_AIRMID_WATER = {
    CULTIVATION_NAME_KEY: "Pour Airmid water (300G)",
    CULTIVATION_COST_KEY: 300,
    CULTIVATION_TIER_KEY: 2,
}

PRUNE = {
    CULTIVATION_NAME_KEY: "Prune (500G)",
    CULTIVATION_COST_KEY: 500,
    CULTIVATION_TIER_KEY: 3,
}

SCATTER_BONEMEAL = {
    CULTIVATION_NAME_KEY: "Scatter Bonemeal (1,000G)",
    CULTIVATION_COST_KEY: 1000,
    CULTIVATION_TIER_KEY: 4,
}

USE_CALEDONIAN_SOIL = {
    CULTIVATION_NAME_KEY: "Use Caledonian soil (1,500G)",
    CULTIVATION_COST_KEY: 1500,
    CULTIVATION_TIER_KEY: 5,
}

SPREAD_PEGASUS_BLESSINGS = {
    CULTIVATION_NAME_KEY: "Spread pegasus blessings (2,000G)",
    CULTIVATION_COST_KEY: 2000,
    CULTIVATION_TIER_KEY: 6,
}
